sudo: required
dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2"
  - "pypy3"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsodium23
  - "python -m pip install -U pip setuptools"

script:
  - "python -m unittest discover --start-directory tests -v"

# until the libsodium source is approved by Travis
# addons:
  # apt:
    # sources:
    # - chris-lea/libsodium
    # packages:
    # - libsodium13
